import {ACTION_CONTROLLER_ACTION} from "./server/src/shared/types/CONTROLLER_ACTION";

const sprawdzone: ACTION_CONTROLLER_ACTION[] = [
    ACTION_CONTROLLER_ACTION.REROLL_ACTION_DICE,
    ACTION_CONTROLLER_ACTION.RESOLVE_ADVENTURE,
    
]
