import {ADVENTURE_CARD_BUILD} from "../../../interfaces/AdventureService/ADVENTURE_CARD";


export const buildAdventureCards: ADVENTURE_CARD_BUILD[] = [
    ADVENTURE_CARD_BUILD.ACCIDENT,
    ADVENTURE_CARD_BUILD.BREAKDOWN,
    ADVENTURE_CARD_BUILD.BROKEN_LEVER,
    ADVENTURE_CARD_BUILD.CONSTRUCTION,
    ADVENTURE_CARD_BUILD.CONSTRUCTION_IS_WEAK,
    ADVENTURE_CARD_BUILD.CUT_HEAD,
    ADVENTURE_CARD_BUILD.DANGEROUS_WORK,
    ADVENTURE_CARD_BUILD.DARK_CLOUDS_IN_THE_SKY,
    ADVENTURE_CARD_BUILD.HARD_WORK,
    ADVENTURE_CARD_BUILD.IN_A_HURRY,
    ADVENTURE_CARD_BUILD.LABORIOUS_WORK,
    ADVENTURE_CARD_BUILD.MONKEYS_WATCH_YOU,
    ADVENTURE_CARD_BUILD.NASTY_WOUND,
    ADVENTURE_CARD_BUILD.SAVINGS,
    ADVENTURE_CARD_BUILD.TIRED,
    ADVENTURE_CARD_BUILD.UNMOTIVATED,
    ADVENTURE_CARD_BUILD.WIND_STORM,
]