import {ADVENTURE_CARD_EXPLORE} from "../../../interfaces/AdventureService/ADVENTURE_CARD";

export const exploreAdventureCards: ADVENTURE_CARD_EXPLORE[] = [
    ADVENTURE_CARD_EXPLORE.CARCASS,
    ADVENTURE_CARD_EXPLORE.COLD_WIND,
    ADVENTURE_CARD_EXPLORE.DANGEROUS_TERRAIN,
    ADVENTURE_CARD_EXPLORE.IT_WILL_RAIN,
    ADVENTURE_CARD_EXPLORE.LOST_IN_THE_WOODS,
    ADVENTURE_CARD_EXPLORE.OLD_GRAVE,
    ADVENTURE_CARD_EXPLORE.OLD_HUT,
    ADVENTURE_CARD_EXPLORE.REMAINS_OF_A_SETTLEMENT,
    ADVENTURE_CARD_EXPLORE.SHRINE,
    ADVENTURE_CARD_EXPLORE.STORM_ON_THE_HORIZON,
    ADVENTURE_CARD_EXPLORE.SWAMP,
    ADVENTURE_CARD_EXPLORE.THERES_SOMETHING_IN_THE_AIR,

]