import {ADVENTURE_CARD_GATHER} from "../../../interfaces/AdventureService/ADVENTURE_CARD";

export const gatherEventCards: ADVENTURE_CARD_GATHER[] = [
    ADVENTURE_CARD_GATHER.AFTER_THE_HURRICANE,
    ADVENTURE_CARD_GATHER.END_OF_SOURCE,
    ADVENTURE_CARD_GATHER.GOLD_COIN,
    ADVENTURE_CARD_GATHER.MUSHROOMS,
    ADVENTURE_CARD_GATHER.NESTLINGS,
    ADVENTURE_CARD_GATHER.NEW_FLOCK,
    ADVENTURE_CARD_GATHER.NICE_SURPRISE,
    ADVENTURE_CARD_GATHER.SHORTAGE,
    ADVENTURE_CARD_GATHER.SIGNS_OF_A_PREDATOR,
    
];