import {ADVENTURE_CARD_GATHER} from "../../../interfaces/AdventureService/ADVENTURE_CARD";

export const gatherAdventureCards: ADVENTURE_CARD_GATHER[] = [
    ADVENTURE_CARD_GATHER.AFTER_THE_HURRICANE,
    ADVENTURE_CARD_GATHER.END_OF_SOURCE,
    ADVENTURE_CARD_GATHER.GOLD_COIN,
    ADVENTURE_CARD_GATHER.MUSHROOMS,
    ADVENTURE_CARD_GATHER.NESTLINGS,
    ADVENTURE_CARD_GATHER.NEW_FLOCK,
    ADVENTURE_CARD_GATHER.NICE_SURPRISE,
    ADVENTURE_CARD_GATHER.SHORTAGE,
    ADVENTURE_CARD_GATHER.SIGNS_OF_A_PREDATOR,
    ADVENTURE_CARD_GATHER.TRACKS_OF_A_PREDATOR,
    ADVENTURE_CARD_GATHER.UNBELIEVABLE_EFFORT,
    ADVENTURE_CARD_GATHER.UNEXPECTED_DISCOVERY,
    ADVENTURE_CARD_GATHER.UNEXPECTED_TROUBLES,
    ADVENTURE_CARD_GATHER.VIPER,
    ADVENTURE_CARD_GATHER.WEATHER_BREAKDOWN,
    ADVENTURE_CARD_GATHER.WINTER_FREEZING,
    ADVENTURE_CARD_GATHER.WINTER_IS_COMING,
];