export enum CREATURE_MYSTERY_CARD {
  A_SHINY_JEWEL = "a shiny jewel",
  BATS = "bats",
  BIG_APE = "big ape",
  BITE = "bite",
  FURIOUS_TIGER = "furious tiger",
  GIANT_SNAKE = "giant snake",
  GORILLA = "gorilla",
  GREMLINS = "gremlins",
  SAVAGE = "savage",
  SCORPION = "scorpion",
  SNAKE = "snake",
  SPIDERS = "spiders",
  UNLEASHED_BEAST = "unleashed beast",
}

export enum TRAP_MYSTERY_CARD {
  BLOW_GUN = "blow gun",
  BLUNT_SPEAR = "blunt spear",
  COLLAPSE = "collapse",
  CONFUSED = "confused",
  HIDDEN_ROPE = "hidden rope",
  NET = "net",
  POISON = "poison",
  SHARP_BLADE = "sharp blade",
  SPIDER_WEB = "spider web",
  STRANGE_DISEASE = "strange disease",
  TERRIBLE_SCREAM = "terrible scream",
  TRAP_DOOR = "drap door",
  UNFORTUNATE_ADVENTURE = "unfortunate adventure",
}

export enum TREASURE_MYSTERY_CARD {
  AMULET_WITH_PORTRAIT_OF_BEAUTIFUL_LADY = "amulet with portrait of beautiful lady",
  ANTIQUE_RAPIER = "antique rapier",
  BACKPACK = "backpack",
  BARREL = "barrel",
  BLANKETS = "blankets",
  BOTTLE_OF_WINE = "bottle of wine",
  BOXES = "boxes",
  CANDLES = "candles",
  CAPTAIN_STONES_SPYGLASS = "captain stones spyglass",
  CAVE_WITH_FURS = "cave with furs",
  CEREMONIAL_BOWL = "ceremonial bowl",
  COMPASS = "compass",
  CROCKS = "crocks",
  GOLD = "gold",
  HAMMOCK = "hammock",
  HATCHED = "hatched",
  HELMET = "helmet",
  HERBAL_MIXTURE = "herbal mixture",
  OLD_CLOTHES = "old clothes",
  OLD_MAP = "old map",
  OLD_RIFLE = "old rifle",
  PROTECTIVE_AMULET = "protective amulet",
  ROPES = "ropes",
  SABRE = "sabre",
  TREASURE_MAP = "treasure map",
}
