export enum INVENTION_PL {
  invention = "karta pomysłu",
  bricks = "cegły",
  medicine = "lek",
  dam = "tama",
  fire = "ogień",
  knife = "nóż",
  map = "mapa",
  pot = "naczynia",
  rope = "lina",
  shovel = "łopata",
  belts = "pasy",
  bow = "łuk",
  lantern = "latarnia",
  moat = "ogrodzene",
  shield = "tarcza",
  wall = "mur",
  fireplace = "palenisko",
  axe = "siekiera",
  mast = "maszt",
}
