export enum TOKEN_PL {
  candles = "świece",
  fallenTree = "powalone drzewo",
  goat = "koza",
  nourishingLarvae = "pożywne larwy",
  healingHerbs = "zioła",
  herbs = "przyprawy",
  largeLeaves = "wielkie liście",
  oldMachete = "stara maczeta",
  poison = "trujące pędy",
  treasure = "znalezisko",
  thornyBushes = "cierniste krzewy",
  tobacco = "tytoń",
  vegetables = "jadalne kłącza",
  oil = "oliwa",
  pirateSaber = "szabla pirata",
  castaways1 = "zioła",
  castaways2 = "oliwa",
  castaways3 = "szabla pirata",
  castaways4 = "medalik z portretem kobiety",
}
